In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv('iris.csv')

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0     0.0  
1     0.0  
2     0.0  
3     0.0  
4     0.0

In [6]:
df.shape

(150, 5)

In [7]:
#train test split using sklearn method
from sklearn.model_selection import train_test_split
features = df.drop('target',axis=1).values
label = df['target'].values
X_train,X_test,y_train,y_test = train_test_split(features,label,test_size=0.2,random_state=33)

In [12]:
X_train = torch.Tensor(X_train)
X_test = torch.Tensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1)
y_test = torch.LongTensor(y_test).reshape(-1,1)

In [15]:
#train test split using PYTORCH and DATALOADER
from torch.utils.data import TensorDataset,DataLoader

In [16]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

In [17]:
data = df.drop('target',axis=1).values
labels = df['target'].values

In [18]:
iris = TensorDataset(torch.Tensor(data),torch.LongTensor(labels))

In [19]:
type(iris) #its a TensorDataset object

torch.utils.data.dataset.TensorDataset

In [20]:
len(iris)

150

In [21]:
for i in iris:
    print(i)

(tensor([5.1000, 3.5000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.0000, 1.4000, 0.2000]), tensor(0))
(tensor([4.7000, 3.2000, 1.3000, 0.2000]), tensor(0))
(tensor([4.6000, 3.1000, 1.5000, 0.2000]), tensor(0))
(tensor([5.0000, 3.6000, 1.4000, 0.2000]), tensor(0))
(tensor([5.4000, 3.9000, 1.7000, 0.4000]), tensor(0))
(tensor([4.6000, 3.4000, 1.4000, 0.3000]), tensor(0))
(tensor([5.0000, 3.4000, 1.5000, 0.2000]), tensor(0))
(tensor([4.4000, 2.9000, 1.4000, 0.2000]), tensor(0))
(tensor([4.9000, 3.1000, 1.5000, 0.1000]), tensor(0))
(tensor([5.4000, 3.7000, 1.5000, 0.2000]), tensor(0))
(tensor([4.8000, 3.4000, 1.6000, 0.2000]), tensor(0))
(tensor([4.8000, 3.0000, 1.4000, 0.1000]), tensor(0))
(tensor([4.3000, 3.0000, 1.1000, 0.1000]), tensor(0))
(tensor([5.8000, 4.0000, 1.2000, 0.2000]), tensor(0))
(tensor([5.7000, 4.4000, 1.5000, 0.4000]), tensor(0))
(tensor([5.4000, 3.9000, 1.3000, 0.4000]), tensor(0))
(tensor([5.1000, 3.5000, 1.4000, 0.3000]), tensor(0))
(tensor([5.7000, 3.8000, 1.7

In [24]:
iris_loader = DataLoader(iris,batch_size=10,shuffle = True)
#divide the data in batches and shuffles it internally

In [25]:
for i_batch,sample_batch in enumerate(iris_loader):
    #iris tensordataset object as per batches(#serial number of the the batch,batch data)
    print(i_batch,sample_batch)

0 [tensor([[6.0000, 3.4000, 4.5000, 1.6000],
        [5.0000, 3.6000, 1.4000, 0.2000],
        [6.8000, 3.2000, 5.9000, 2.3000],
        [6.7000, 3.3000, 5.7000, 2.5000],
        [7.7000, 2.6000, 6.9000, 2.3000],
        [7.2000, 3.6000, 6.1000, 2.5000],
        [5.1000, 3.7000, 1.5000, 0.4000],
        [5.0000, 3.0000, 1.6000, 0.2000],
        [5.7000, 3.8000, 1.7000, 0.3000],
        [4.4000, 3.2000, 1.3000, 0.2000]]), tensor([1, 0, 2, 2, 2, 2, 0, 0, 0, 0])]
1 [tensor([[5.4000, 3.7000, 1.5000, 0.2000],
        [5.8000, 2.7000, 4.1000, 1.0000],
        [7.4000, 2.8000, 6.1000, 1.9000],
        [7.0000, 3.2000, 4.7000, 1.4000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [6.7000, 3.0000, 5.2000, 2.3000],
        [5.1000, 2.5000, 3.0000, 1.1000],
        [5.1000, 3.3000, 1.7000, 0.5000],
        [5.0000, 3.4000, 1.6000, 0.4000],
        [4.8000, 3.4000, 1.6000, 0.2000]]), tensor([0, 1, 2, 1, 0, 2, 1, 0, 0, 0])]
2 [tensor([[5.2000, 2.7000, 3.9000, 1.4000],
        [5.9000, 3.2000, 

In [26]:
#generally keeping track of batch number is not important so we use:
for batch in iris_loader:
    print(batch)

[tensor([[6.5000, 3.2000, 5.1000, 2.0000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.5000, 2.4000, 3.7000, 1.0000],
        [6.3000, 2.5000, 4.9000, 1.5000],
        [5.6000, 2.9000, 3.6000, 1.3000],
        [6.3000, 3.4000, 5.6000, 2.4000],
        [5.0000, 3.3000, 1.4000, 0.2000],
        [6.5000, 2.8000, 4.6000, 1.5000],
        [6.1000, 2.9000, 4.7000, 1.4000],
        [6.4000, 2.9000, 4.3000, 1.3000]]), tensor([2, 0, 1, 1, 1, 2, 0, 1, 1, 1])]
[tensor([[7.0000, 3.2000, 4.7000, 1.4000],
        [5.6000, 2.7000, 4.2000, 1.3000],
        [5.4000, 3.9000, 1.3000, 0.4000],
        [5.8000, 2.7000, 3.9000, 1.2000],
        [4.9000, 3.1000, 1.5000, 0.1000],
        [4.5000, 2.3000, 1.3000, 0.3000],
        [6.2000, 2.2000, 4.5000, 1.5000],
        [5.5000, 4.2000, 1.4000, 0.2000],
        [5.9000, 3.0000, 5.1000, 1.8000],
        [5.7000, 3.0000, 4.2000, 1.2000]]), tensor([1, 1, 0, 1, 0, 0, 1, 0, 2, 1])]
[tensor([[7.6000, 3.0000, 6.6000, 2.1000],
        [5.1000, 3.5000, 1.4000