# 1

## Tensor Basics

In [1]:
import torch

In [2]:
import numpy as np
torch.__version__

'1.13.1'

In [3]:
arr=np.array([1,2,3,4,5])

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
arr.dtype

dtype('int32')

In [6]:
type(arr)

numpy.ndarray

In [8]:
x=torch.from_numpy(arr) #torch.as_tensor(arr) can also be used

In [9]:
type(x)

torch.Tensor

In [10]:
x

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [11]:
x.dtype

torch.int32

In [13]:
arr2d = np.arange(0.0,12.0)

In [14]:
arr2d

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
arr2d = arr2d.reshape(4,3)

In [16]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [17]:
x2 = torch.from_numpy(arr2d)

In [18]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [19]:
arr[0]=99
arr

array([99,  2,  3,  4,  5])

In [20]:
x

tensor([99,  2,  3,  4,  5], dtype=torch.int32)

In [21]:
#we can see the chnage in original array effects the tensor as well and as we dont want this we use:

In [23]:
my_arr = np.arange(0,10)
my_tensor = torch.tensor(my_arr)#this does not create a direct link between the tensor and the array

In [25]:
my_other_tensor = torch.from_numpy(my_arr)

In [27]:
print(my_arr)
print(my_tensor)
print(my_other_tensor)

[0 1 2 3 4 5 6 7 8 9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [28]:
my_arr[0]=99
print(my_arr)
print(my_tensor)
print(my_other_tensor)

[99  1  2  3  4  5  6  7  8  9]
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)
tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)


In [29]:
#as we can see the change affects my other tensor but the other one is unaffected

In [32]:
new_arr = np.array([1,2,3])

In [33]:
torch.tensor(new_arr)

tensor([1, 2, 3], dtype=torch.int32)

In [35]:
tne=torch.Tensor(new_arr)

In [36]:
tne.dtype

torch.float32

In [37]:
#torch.tensor retains the datatype meanwhile Tensor gives float dtype to the datatype

In [38]:
torch.empty(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [40]:
torch.zeros(2,2,dtype=torch.int32)

tensor([[0, 0],
        [0, 0]], dtype=torch.int32)

In [41]:
torch.zeros(2,2,dtype=torch.int64)

tensor([[0, 0],
        [0, 0]])

In [43]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [45]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [46]:
torch.linspace(0,18,12)

tensor([ 0.0000,  1.6364,  3.2727,  4.9091,  6.5455,  8.1818,  9.8182, 11.4545,
        13.0909, 14.7273, 16.3636, 18.0000])

In [47]:
my_tensor = torch.tensor([1,2,3])

In [48]:
my_tensor.dtype

torch.int64

In [49]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [52]:
my_tensor

tensor([1, 2, 3])

In [53]:
my_tensor = my_tensor.type(torch.int32) #to change the dtype we need to assign the change

In [54]:
my_tensor

tensor([1, 2, 3], dtype=torch.int32)

In [55]:
torch.rand(4,3)

tensor([[0.4911, 0.0505, 0.7762],
        [0.0335, 0.1980, 0.6706],
        [0.9945, 0.9792, 0.5581],
        [0.0778, 0.0636, 0.1486]])

In [56]:
torch.randn(4,3)

tensor([[-0.9258, -2.6358,  0.2973],
        [ 0.5260,  1.6504,  1.2285],
        [ 0.6490,  0.2684,  0.7280],
        [-1.3847,  0.8828,  1.8247]])

In [58]:
torch.randint(low=0,high=10,size=(10,10))

tensor([[2, 2, 0, 8, 6, 8, 0, 8, 8, 0],
        [6, 7, 3, 3, 2, 5, 5, 5, 8, 8],
        [2, 7, 4, 9, 0, 3, 5, 8, 2, 5],
        [4, 9, 8, 6, 7, 7, 7, 7, 3, 1],
        [5, 0, 0, 7, 4, 1, 2, 8, 5, 7],
        [2, 3, 7, 7, 6, 6, 8, 7, 5, 4],
        [7, 8, 3, 7, 5, 3, 4, 9, 0, 4],
        [6, 8, 5, 0, 7, 5, 8, 0, 0, 9],
        [7, 1, 5, 5, 2, 3, 5, 0, 2, 7],
        [1, 2, 9, 2, 5, 8, 5, 2, 8, 5]])

In [59]:
x = torch.zeros(2,5)

In [60]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [63]:
torch.rand_like(x)#helps pass on the shape/characterstics of the x tensor

tensor([[0.8081, 0.0320, 0.2592, 0.5229, 0.4878],
        [0.9030, 0.9923, 0.3247, 0.0545, 0.0372]])

In [64]:
torch.randn_like(x)

tensor([[-0.1734, -0.4417,  0.5526,  0.8943, -0.2650],
        [ 0.5197, -1.4162, -0.9799,  0.3047, -0.8577]])

In [67]:
torch.randint_like(x,low=0,high=10)

tensor([[2., 7., 3., 1., 7.],
        [3., 6., 9., 7., 3.]])

In [73]:
torch.manual_seed(42)

In [75]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

In [74]:
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [72]:
torch.rand(2,3)

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

## Tensor Operations

In [79]:
x=torch.arange(6).reshape(3,2)

In [80]:
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [81]:
x[1,1]

tensor(3)

In [82]:
type(x[1,1])

torch.Tensor

In [83]:
x[:,1]

tensor([1, 3, 5])

In [84]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [85]:
x = torch.arange(10)

In [86]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [88]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [90]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
#almost the same

In [92]:
x = x.reshape(2,5)

In [93]:
x

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [95]:
x = x.reshape(10,)

In [96]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
z = x.view(2,5)

In [98]:
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [99]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
x[0]=99
x

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [102]:
z

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [103]:
x[0]=0

In [104]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
x.shape

torch.Size([10])

In [106]:
x.view(2,-1) #finds out the second dim

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [108]:
x.view(3,-1)#gives error if first dim is wrong

RuntimeError: shape '[3, -1]' is invalid for input of size 10

In [109]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [110]:
a

tensor([1., 2., 3.])

In [111]:
b

tensor([4., 5., 6.])

In [112]:
a+b

tensor([5., 7., 9.])

In [113]:
a.mul(b)

tensor([ 4., 10., 18.])

In [114]:
a

tensor([1., 2., 3.])

In [115]:
a.mul_(b)#assigns the result back to a

tensor([ 4., 10., 18.])

In [116]:
a

tensor([ 4., 10., 18.])

In [117]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [119]:
a*b #element by element multiplication

tensor([ 4., 10., 18.])

In [120]:
a.dot(b) #dot product

tensor(32.)

In [123]:
a=torch.randint(low=1,high=5,size=(2,3))

In [124]:
a

tensor([[4, 3, 2],
        [1, 2, 4]])

In [125]:
b=torch.randint(low=1,high=5,size=(3,2))

In [126]:
b

tensor([[4, 2],
        [2, 2],
        [4, 4]])

In [127]:
a.shape


torch.Size([2, 3])

In [128]:
b.shape

torch.Size([3, 2])

In [129]:
torch.mm(a,b)#mathematical multiplication

tensor([[30, 22],
        [24, 22]])

In [130]:
a@b

tensor([[30, 22],
        [24, 22]])

In [134]:
x= torch.tensor([2.,3.,4.,5.])

In [135]:
x

tensor([2., 3., 4., 5.])

In [136]:
x.norm()

tensor(7.3485)

In [137]:
x.numel()

4

In [138]:
len(x)

4

In [139]:
a

tensor([[4, 3, 2],
        [1, 2, 4]])

In [140]:
len(a)

2

In [141]:
a.numel()

6

# 2